### ISSUE TITLE
migrating to new log entries

### ISSUE THREAD

**Issue by eroux** [buda-base/xmltoldmigration#127]
@xristy I'm going to need your help on this... Here are a few interesting things to look at:
- [I0886](https://www.tbrc.org/xmldoc?rid=I0886) has a qc date, I think we could give it its own log entry, which could be a new `adm:ContentQCLogEntry`?
- [I0886](https://www.tbrc.org/xmldoc?rid=I0886) and [W22084](https://www.tbrc.org/xmldoc?rid=W22084) have a first log entry that clearly doesn't represent their creation... I'm thinking maybe we should add the graph creation log entry only on the RID that are in the new form, like [W4CZ309048](https://www.tbrc.org/xmldoc?rid=W4CZ309048) (or perhaps the dlms has a default commit message for the creation?)
- still in [I0886](https://www.tbrc.org/xmldoc?rid=I0886), I think the line `<ig:scanning initiated="true" complete="true">Satluj Siti Enterprises</ig:scanning>` could be transformed into a content creation log entry with a log message (and no date)?
- what user is the sync script? am I right to say that all the entries with `who="Imagegroups Updater"` are sync entries? Has the user ever changed? I don't think the message `Updated total pages` is an unambiguous indication of the sync process as some other scripts have the same message, like in [I0886](https://www.tbrc.org/xmldoc?rid=I0886)

related to https://github.com/buda-base/owl-schema/issues/170

**Comment by xristy** [comment]
> I0886 has a qc date, I think we could give it its own log entry, which could be a new adm:ContentQCLogEntry?

That can be done; however, that info was not collected after the earliest volumes were scanned since formal attempts at qc'ing were abandoned

> I0886 and W22084 have a first log entry that clearly doesn't represent their creation... I'm thinking maybe we should add the graph creation log entry only on the RID that are in the new form, like W4CZ309048 (or perhaps the dlms has a default commit message for the creation?)

The dlms editor doesn't have a default creation message.

We could use `:notAfter` for the _old format_ RIDs. Notice for example that I0866 ... were marked as qc'd in 2003. The records in eXist-db were migrated from the MySql in 2005 or so and there was no creation date kept in MySql.

> still in I0886, I think the line <ig:scanning initiated="true" complete="true">Satluj Siti Enterprises</ig:scanning> could be transformed into a content creation log entry with a log message (and no date)?

You could do that. I don't know how helpful it would be.

> what user is the sync script? am I right to say that all the entries with who="Imagegroups Updater" are sync entries? 

Yes those are sync entries

> Has the user ever changed? 

Yes. I've changed the user several times. Most recently it seemed a good idea to use the name of the script when applicable so I'd have some idea what code did the work.

> I don't think the message Updated total pages is an unambiguous indication of the sync process as some other scripts have the same message, like in I0886

The phrase "Updated total pages" is only used for sync'ing. It sometimes happens that a sync has run at two different times. Usually to correct for some error - image reordering or duplicate deletion, etc.

**Comment by eroux** [comment]
> That can be done; however, that info was not collected after the earliest volumes were scanned since formal attempts at qc'ing were abandoned

ok yes, let's do that then

Let's give up on the not after for the creation... if we don't know we don't know, that's fine

> You could do that. I don't know how helpful it would be.

Well, we would know that the scanning was made by *Satluj Siti Enterprises*. But actually this info is more commonly put in the scanInfo field... maybe I should just put it there...?

> The phrase "Updated total pages" is only used for sync'ing. It sometimes happens that a sync has run at two different times. Usually to correct for some error - image reordering or duplicate deletion, etc.

Oh ok! So in that case there were two syncs, one in 2016 and one in 2020? Or three counting `Updated total pages and added page list`?

Finally it seems to me that these entries:

```xml
<entry when="2016-03-30T12:20:30.571-04:00" who="Code Ferret">Updated total pages</entry>
<entry when="2016-03-31T17:27:09.458-04:00" who="Code Ferret">Added ondisk</entry>
```

are common to all the works that were on tbrc.org around 2016 right? (I'm not sure what to do with that info, but... that's something)

**Comment by xristy** [comment]
I think putting the scanning text from the imagegroup in the `bdo:scanInfo` on `Instance`s makes most sense.

> Oh ok! So in that case there were two syncs, one in 2016 and one in 2020? Or three counting Updated total pages and added page list?

The phrase "added page list" was transient on the imagegroup-updater scripts since we were still modifying the sync flow.

Initially in late March of 2016 there was a batch run just to add total page info for some works from a csv.
Then just `onDisk` info was added with no page list:
```
<ig:description type="ondisk"/>
```

And a bit later imagegroup-updater was modified to have:
```
<ig:description type="ondisk">{$pageList}</ig:description>
```
Along with updating the total pages as in:
```
<ig:images total="624" tbrcintro="2" intro="0" text="620"/>
```

**Comment by eroux** [comment]
Ok! So, to summarize and check that I understood correctly:

```xml
<entry when="2016-03-30T12:20:30.571-04:00" who="Code Ferret">Updated total pages</entry>
```

is sync,

```xml
<entry when="2016-03-31T17:27:09.458-04:00" who="Code Ferret">Added ondisk</entry>
```

is graph modification,

```xml
<entry when="2016-04-28T23:50:58.855Z" who="Code Ferret">Updated total pages and added page list</entry>
```

is graph modification

```xml
<entry when="2020-01-08T22:37:32.318Z" who="Imagegroups Updater">Updated total pages</entry>
```

is sync.

Does it sound right?

**Comment by xristy** [comment]
> `<entry when="2016-03-30T12:20:30.571-04:00" who="Code Ferret">Updated total pages</entry>`
is sync,

it was an early updating of some bookkeeping in the imagegroup record. The actual sync'ing of images to archive had already happened sometime in the past. The March 2016 timeframe was when we started encoding info in the imagegroup record to support better S3 usage. In the days before using AWS the app server simply interrogated the local disk for whether images were present or not for a given volume. There was a, relatively short, period of developing the info that would be recorded in the imagegroup records to avoid treating S3 as a local disk which is why there are a bunch of odd records around that time.

> `<entry when="2016-03-31T17:27:09.458-04:00" who="Code Ferret">Added ondisk</entry>`
is graph modification,

This and the above can be considered graph modification or an upper bound on the sync date (which may or not be useful)

> `<entry when="2016-04-28T23:50:58.855Z" who="Code Ferret">Updated total pages and added page list</entry>`
is graph modification

by this point these should be syncs. The imagegroup-updater sets the onDisk, page list, and total page info at the tme of sync'ing

> `<entry when="2020-01-08T22:37:32.318Z" who="Imagegroups Updater">Updated total pages</entry>`
is sync.

This is the same as the just previous record except I substituted the script info instead of my username and truncated the message.

I'm sorry this is confused, but there was a bit of implementing part of the system while it was in production. It's taken a bit of today for me to dredge up the memories.

**Comment by eroux** [comment]
Excellent, thanks!

**Comment by eroux** [comment]
What about the following algorithm:

```
type = graphupdate
if message.startswith("Updated total pages"):
   if date not in [ "2016-03-31T17:27:09.458-04:00", "2016-04-28T23:50:58.855Z", "2016-04-28T23:50:58.855Z"]:
       type = sync
```

?

I think the `"2016-04-28T23:50:58.855Z"` entry is not really a sync neither as it seems to have occured in all image groups, for instance [I3207](https://www.tbrc.org/xmldoc?rid=I3207)

**Comment by xristy** [comment]
Yes that's apparently part of the attempt to get the eXist-db consistent with the S3 archive

**Comment by eroux** [comment]
ok, I'll implement that!

**Comment by eroux** [comment]
@xristy I think we should have a better detection of the moment of creation of a graph/file... I'm wondering if this algorithm would work:

```
if RID matches "^[A-Z]+\d+$":
   # example: W22084, denoting a pre-dlms record?
   if first_log_entry starts with "new " or "create" or "add new ":
       first_log_entry_type = creation
else:
   # example W2PD17468, denoting a dlms record?
   first_log_entry_type = creation
```

would that work?

**Comment by xristy** [comment]
I really don't know if that works. Do you have some examples? I don't think we have any graph creation info for pre-dlms records. It seems to me we can just use the `adm:UpdateGraph` and remain silent on creation of those records unless you want to use `:notAfter` based on the earliest dated info.

**Comment by eroux** [comment]
hmmm I think it's what I'm doing in my algorithm? I guess another way to ask the same question is: 

Am I right to say that:
- if RID doesn't match `^[A-Z]+\d+$` then we have a dlms record and the first log entry is the creation entry
- otherwise we can only make some guess based on the log message
?

**Comment by eroux** [comment]
just to clarify, `^[A-Z]+\d+$` matches RIDs with some letters at the beginning, and then only numbers, such as `W22084` or `P1583`

**Comment by xristy** [comment]
Yes I understand the regex. 

I was not agreeing that the earliest logentry represents creation of the record. 

If there must be a creation record then it should read like 

      "created before adm:LogDate of this adm:CreateGraph entry"

**Comment by eroux** [comment]
Here are some interesting exceptions to our model / migration:
- now that the image groups are in the same graph as the image instance, we have different `adm:CreateGraph` per graph, which is a bit confusing... maybe for image groups (and pub infos?) we should have a `adm:CreateRecord`, something like that?
- for imported records (FEMC, NLM, like [this one](https://www.tbrc.org/xmldoc?rid=W1FEMC023248) we have a log entry for the creation of the catalog, and a log entry for the import... I think none of these really represent the same thing as a `adm:CreateGraph`... perhaps a `adm:ImportGraph` would be useful? I would also use it for our partner data. And for the creation of the catalog, perhaps the same `adm:CreateRecord` as before?

**Comment by eroux** [comment]
Also, in order to have better data we should be able to distinguish between a batch update / import and a manual modification... I think having a `adm:BatchUpdateGraph` would be enough... wdyt?

**Comment by xristy** [comment]
Distinctions:
- manual recording of some metadata about some entity versus mechanical (batch) recording of previously manually recorded metadata entities, e.g., in a spreadsheet representation
- representations of metadata: sql tables versus xml records versus rdf graphs (or models)
- initial materialization of some (coherent cluster of) metadata in some representation versus later updating/modifying of some previously established metadata entity or entities.

Since I am not clear on the extent of what you envision as applications of the recording of various sort of distinctions about the evolution of the metadata (not to mention the contents: image, etext or perhaps pictorial, e.g., tsakle, contents), I'm not sure to what degree distinguishing among representations is helpful or not. 

We can approximate the representations by saying that old-style RIDs were originally recorded as tabular data and the new style RIDs as xml records - there are as yet no metadata entities recorded directly as rdf graphs by our staff although there are some rdf graph representations that are imported from third-parties but do we know whether they were initially recorded as rdf graphs or some other representation and then re-represented as rdf graphs?

We could eschew _graph_ in favor of _metadata_. So `adm: MetadataInitiallyRecorded` instead of `adm:CreateGraph`; and, indicate `adm:MetadataInitiallyRecorded` at a particular **date-time** by some **agent** (person or script) in some **representation** (sql table or spreadsheet can both count as tabular) with some **comment**.

For imagegroups or other embedded entities such as occur w/ outlines we could use `adm:EmbeddedMetadataInitiallyRecorded` or adopt a convention that `adm:MetadataInitiallyRecorded` is used for entities whether embedded or not.

There may be a useful distinction between the creation/importation/recording of a **singleton**/**manual** versus **batch of** / **mechanically derived** distinct clusters of metadata. This suggests an additional property in a log entry to distinguish between the **user** and **agent**. So we would be able to express that:

- **user**:CodeFerret using **agent**:add-works-to-CTC17 on **datetime**:2020-08-18 w/ **comment**:"work added to CTC 17"
- **user**:Karma using **agent**:DLMS-editor on **datetime**:2020-05-21 w/ **comment**:"added new students"

Previously, the pubinfo metadata is usually recorded together with a work's metadata and often published at the same time, for example:

    2017-01-04T14:35:41.680Z for pubinfo
    2017-01-04T14:35:41.955Z for work

but for completeness it seems reasonable to include the creation/importation/recording of the metadata in the (graph) representation.

Since the pubinfo is the basis of Instance metadata versus Work metadata and the two sorts of metadata are generally in distinct graphs it seems appropriate to provide information about the initial recording in each of the graphs

**Comment by xristy** [comment]
I should have added things like `adm:MetadataUpdated`, `adm:MetadataWithdrawn` and so on.

**Comment by xristy** [comment]
The batch versus single entity distinction is established via the **agent**

**Comment by xristy** [comment]
-  **user**:CodeFerret using **agent**:add-works-to-CTC17 on **datetime**:2020-08-18 w/ **comment**:"work added to CTC 17" from **source**: "list of RIDs"
- **user**:Karma using **agent**:DLMS-editor on **datetime**:2020-05-21 w/ **comment**:"added new students" from **source**: "manual"
- **user**:Elie using **agent**:EAP-import on **datetime**:2020-06-17 w/ **comment**:"importing EAP metadata" from **source**: "csv"

**Comment by eroux** [comment]
- I agree with some that the data that we have about a person is data, not metadata... So I would change `Metadata` for `Data`... but yes, let's not use `Graph` as it's a more loaded term. This requires some changes in owl-schema
- I agree with the agent thing yes. What agent should I record for the first 3 log entries of [I0886](https://www.tbrc.org/xmldoc?rid=I0886)? the sync script? This also requires some changes in owl-schema. I'm a bit opposed to adding an agent for all the normal entries though, that seems a little bit gratuitous...
- I agree with the work vs. instance thing yes, why not... some of the log entries will disappear when two works are merged, but it's fine I think... or actually I realize that the best is probably to migrate them anyways and mark the record as withdrawn, that would be the best option.
- Having a source would be good yes, but we don't have any data so we can keep that for later... and even for the FEMC, the main data source is the FEMC catalog, the staff in Cambodia just inputted it... so there's a source of the source... all of that is very good data to have but it's also very marginal so I would stick to something simple for now, like `ImportedDataCreated`

**Comment by xristy** [comment]
There are various observables regarding an entity, such as weight and linear dimensions. There are also items of convention such as birth-date, name and title, students, authors and so on. We can agree to refer to all of this as **data** and then bits such as log-entries and repo-id and version-id are **metadata**.  So only `adm:` is **metadata**.

**Comment by eroux** [comment]
I'm almost done with the changes but there is still one case that we should clarify: outlines. They have their own log entries and they are currently merged with the instance (because the two entities merged). It's not totally unreasonable, but I'm thinking we should distinguish the log entries in order to attribute things properly... I think if we have something like

```ttl
adm:UpdateOutlineData rdfs:subClassOf adm:UpdateData .
adm:CreateOutlineData rdfs:subClassOf adm:UpdateData .
```

(but the second could also be a subclass of `adm:InitialDataCreation`). wdyt?

**Comment by xristy** [comment]
I'll add

    adm:UpdateOutlineData rdfs:subClassOf adm:UpdateData .
    adm:InitialOutlineData rdfs:subClassOf adm:InitialDataCreation .

**Comment by eroux** [comment]
Doing the code I realized `adm:InitialOutlineDataImport` is also necessary

**Comment by xristy** [comment]
I was thinking that also

    adm:InitialOutlineDataImport rdfs:subClassOf adm:InitialDataImport .

**Comment by xristy** [comment]
Just checking the migration to testrw I see at least one problem. In bdg:W1 I see:
```
bda:LGIGS001  a         adm:UpdateData ;
        adm:logDate     "2016-03-30T16:20:30.571Z"^^xsd:dateTime ;
        adm:logMessage  "Updated total pages"@en ;
        adm:logMethod   bda:BatchMethod ;
        adm:logWho      <http://purl.bdrc.io/resource-nc/user/U00006> .
bda:LGIGS002  a         adm:UpdateData ;
        adm:logDate     "2016-03-31T21:27:09.458Z"^^xsd:dateTime ;
        adm:logMessage  "Added ondisk"@en ;
        adm:logMethod   bda:BatchMethod ;
        adm:logWho      <http://purl.bdrc.io/resource-nc/user/U00006> .
bda:LGIGS003  a         adm:UpdateData ;
        adm:logDate     "2016-04-28T23:50:58.855Z"^^xsd:dateTime ;
        adm:logMessage  "Updated total pages and added page list"@en ;
        adm:logMethod   bda:BatchMethod ;
        adm:logWho      <http://purl.bdrc.io/resource-nc/user/U00006> .
```




and in W01CT0060
```
bda:LGIGS001  a  adm:UpdateData .

bda:LGIGS002  a         adm:UpdateData ;
        adm:logDate     "2016-03-31T21:27:09.458Z"^^xsd:dateTime ;
        adm:logMessage  "Added ondisk"@en ;
        adm:logMethod   bda:BatchMethod ;
        adm:logWho      <http://purl.bdrc.io/resource-nc/user/U00006> .
```

This is going to make a bit of a mess I fear.

**Comment by eroux** [comment]
Hmm it's on purpose... what kind of mess are you anticipating?

**Comment by xristy** [comment]
I guess its fine it you intend it. You'll know what sort of queries to write and so on. Most of the log entries in instances and persons and so on use a 16 hex-digit id along with many other _internal_ ids. So these caught my attention since they obviously aren't trying to be unique except within a given graph

What are you encoding in the ids this way?

**Comment by eroux** [comment]
In the id of the log entries? Nothing, I just generate one id per batch change on the same timestamp

**Comment by xristy** [comment]
ok. That doesn't seem true for `bda:LGIGS001`. I'll drop it. It was just unexpected to me.

**Comment by eroux** [comment]
Oh I see what you mean now... sorry, I'm on my phone so things are not very clear, I shall inspect

**Comment by eroux** [comment]
hmmm I just checked and the file on the git repo on buda2 seems fine (`/bdrc-git-repos/iinstances/36/W01CT0060.trig`)... and I see the expected 

```ttl
bda:LGIGS001  a         adm:UpdateData ;
        adm:logDate     "2016-03-30T16:20:30.571Z"^^xsd:dateTime ;
        adm:logMessage  "Updated total pages"@en ;
        adm:logMethod   bda:BatchMethod ;
        adm:logWho      bdu:U00006 .
```

when I query

```sparql
construct {?s ?p ?o} where {
  graph <http://purl.bdrc.io/graph/W01CT0060> { ?s ?p ?o }
}
```

... how did you get the empty

```
bda:LGIGS001  a  adm:UpdateData .
```

?

**Comment by xristy** [comment]
I ran the same query

**Comment by xristy** [comment]
Ah! I had the limit set too low and didn't get the whole graph.

**Comment by eroux** [comment]
aaaaaah I see! interesting

**Comment by eroux** [comment]
I wonder also how the NLM records should be attributed...

**Comment by xristy** [comment]
All of the NLM records have been imported from csv via

    /db/modules/admin/works-nlm-import.xql

and marked as such like:

    <entry when="2018-10-28T18:29:33.12Z" who="NLM Importer">imported W1NLM1</entry>

You may refer to [nlm](https://www.tbrc.org/docs/nlm/) for the logs from various test and import runs.

The attribution is in the `catalogInfo`.

**Comment by eroux** [comment]
Yes, I meant something prior to that... like which librarian created the line of the csv that we imported... but maybe we don't have this data? or is the csv produced in Mongolia?

**Comment by xristy** [comment]
There may be some columns in the master google sheets recording info about staff at the NLM that created particular entries.

@TBRC-Travis is the keeper of the master google sheets that he uses to set up batches for import. The master sheets do have a column for a Mongolian person and a date of entry but from the old versions that I have the date was rarely if ever filled out and the person info was deemed at the time the importing was _designed_ to not be included in our records.

I can no longer find the big giant master sheet on google drive. I'm sure @TBRC-Travis can point to it.

**Comment by xristy** [comment]
As for other batch importing I really don't recall others. From the info I see in the L1RKLnnn I had well forgotten that Ralf's work was originally dealt with in 2007 by Jeff. I think there was more work on the schema done later.

**Comment by eroux** [comment]
ok perfect! I just wasn't sure who was producing the csv, but it's fine this way
