### ISSUE TITLE
using primaryTitle as prefLabel for persons?

### ISSUE THREAD

**Issue by eroux** [buda-base/xmltoldmigration#170]
Currently when we display the name of a person, we take the first name that appears in the data. For instance for https://www.tbrc.org/#!rid=P1583 this is `dri med 'od zer` (this the way it's displayed on both tbrc.org and BUDA). Here the type of name is a `PrimaryName`. I'm starting to wonder if we should perhaps use the first name of type `primaryTitle` instead? It seems this is designed to be a name that is more unique and allows easier discrimination between people with similar names. I propose we use this as the the main name/label of a person on BUDA (I know some users would be happy with that).

@karmagongde @xristy @JannTibetan what do you think?

**Comment by eroux** [comment]
The implications would be that this would be the name that would appear in large bold letter when doing a search on BUDA, and it's also the name that would appear when listing the connections from other entities.

For instance for P1844 the "main name" (that we call preferred label internally) is currently "bsod nams rin chen" because it's the first one that appears on https://www.tbrc.org/#!rid=P1844 . It is displayed when searching it:

https://library.bdrc.io/search?q=%22bsod%20nams%20rin%20chen%22~1&lg=bo-x-ewts&t=Person

and also when it's referred to in the related persons, for instance in the "student of" of https://library.bdrc.io/show/bdr:P1853 (in the same way that it's used on the Associated Persons of https://www.tbrc.org/#!rid=P1853).

The proposed change is to use the first Primary Title of persons as their "main name", so in that case it would be "sgam po pa bsod nams rin chen" instead of "bsod nams rin chen". I think it's better as it's more specific. I know a few scholars who would find that very helpful to have these more prominently displayed in search results, and in related entities.

**Comment by karmagongde** [comment]
In my opinion, we should keep the order of the Person record the same as before. The order of the variant name list could be Gene la's intention.

This will also help BDRC users to learn more about authors with the same _PrimaryName_. By scrolling the list they will imprint the variant authors in the mind.

Besides being the resource, the BDRC website became a textbook to learn other authors' names etc.

Since the website is all searchable, users get all the search result how they want to find out (with or without _PrimaryTitle_). If the users are not sure about the _PrimaryTitle_ they will search through the listed _PrimaryName_.

Also, many of the authors do not have the _PrimaryTitle_ and some have more than one _PrimaryTitle_.

**Comment by eroux** [comment]
> This will also help BDRC users to learn more about authors with the same PrimaryName. By scrolling the list they will imprint the variant authors in the mind.

Well, while I understand the pedagogical aspect for some of our users, but I'm not sure pedagogy should be the priority compared to ease of use and standardization

> Besides being the resource, the BDRC website became a textbook to learn other authors' names etc.

I'm not sure I understand, can you develop?

> Since the website is all searchable, users get all the search result how they want to find out (with or without PrimaryTitle). If the users are not sure about the PrimaryTitle they will search through the listed PrimaryName.

Well, yes, all names are searchable, but this is not really the issue here: another aspect is the standardization of names. For better or worse, this "main name" that we assign will become the standard name for many persons in our database, as it will find its way to Wikidata, VIAF, etc. What databases of names usually do is to avoid duplicate names as much as possible, and this seems like what we're doing for primary titles. This is a new use of our data that didn't exist some years ago, and I think our data should evolve with the ecosystem we're evolving in...

> Also, many of the authors do not have the PrimaryTitle and some have more than one PrimaryTitle.

Yes, that's not an issue, in case there's no PrimaryTitle we can just keep the current one, and when there are two we can take the first one

**Comment by eroux** [comment]
@karmagongde after a discussion with Jann, we're going to move forward with the promotion of the primaryTitle as described above, we can still change it at a later point if there's too much disturbance

**Comment by JannTibetan** [comment]
Dear all, thanks for the two threads about Primary Names and Primary Titles. 
There is often no similarity between a name and title and this can be confusing for users because they often know only the primary title and not the personal name. There are so many examples to cite but just one would be http://library.bdrc.io/show/bdr:P127 Everybody has heard of Pakmodrupa and translations of his works into English, for instance, are attributed to Pakmodrupa and not Dorje Gyalpo. 
The proposal to make Primary Title the main label on the UI will make our person records more user friendly while not altering the data at all. It is just an adjustment of the UI. We are hoping to attract more non-specialists to BDRC and this kind of modification will help with that. Thanks!

**Comment by eroux** [comment]
I agree. The change has been made is now online on BUDA!
