### ISSUE TITLE
bdr:G162 bdo:placeType bdr:PlaceTypeDgonPa

### ISSUE THREAD

**Issue by berger-n** [buda-base/xmltoldmigration#94]
see http://purl.bdrc.io/resource/G162.ttl
it has `bdo:placeType  bdr:PlaceTypeDgonPa`
not in possible values for http://purl.bdrc.io/ontology/core/PlaceType

**Comment by xristy** [comment]
Yes the proper type is `bdr:PT0037`. Now to find where the problem is. 

It seems that [PlaceMigration.java](https://github.com/buda-base/xmltoldmigration/blob/db5b13e3c7415ad1dfc33cb5e4544568777d4eb4/src/main/java/io/bdrc/xmltoldmigration/xml2files/PlaceMigration.java#L56) is using an old resource ids of PlaceTypes rather than the current resource ids like `bdr:PT0037`

So currently none of the `:placeType` values in bdrcrw are in sync with the ontology. For example, [bdr:G601](http://purl.bdrc.io/resource/G601.ttl) shows `bdr:PlaceTypeGrongTsho` instead of `bdr:PT0084`

If the current resource ids in the ontology are used in the 55K+ `:Places` what is going to break?

**Comment by eroux** [comment]
I think it's safe to proceed with the change in the migration
